// lib/cheatsheet.ts
//
// Generates a print-ready, one-page-per-section cheat sheet PDF from your
// existing concept JSON — no new content authoring needed, ever. Every time
// you add a concept, its cheat sheet entry exists automatically.
//
// Install: npm install jspdf

import { jsPDF } from "jspdf";
import type { Concept } from "@/types/concept";

const BRAND_COLOR = "#2563eb"; // swap for your logo/accent color
const MARGIN = 15;
const PAGE_WIDTH = 210; // A4 mm

export function generateCheatsheet(
  sectionTitle: string,
  concepts: Concept[]
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(BRAND_COLOR);
  doc.text(`🐦 ${sectionTitle} — Cheat Sheet`, MARGIN, y);
  y += 6;
  doc.setFontSize(9);
  doc.setTextColor("#888888");
  doc.text("Generated by Hummingraph · hummingraph.dev", MARGIN, y);
  y += 10;

  concepts.forEach((concept, i) => {
    const blockHeight = estimateBlockHeight(concept);
    if (y + blockHeight > 285) {
      doc.addPage();
      y = MARGIN;
    }

    // Concept title
    doc.setFontSize(13);
    doc.setTextColor("#111111");
    doc.text(`${i + 1}. ${concept.title}`, MARGIN, y);
    y += 5;

    // Tagline
    doc.setFontSize(9);
    doc.setTextColor("#555555");
    doc.setFont("helvetica", "italic");
    y = wrapText(doc, concept.tagline, MARGIN, y, PAGE_WIDTH - MARGIN * 2);
    doc.setFont("helvetica", "normal");
    y += 2;

    // Key points as bullets
    doc.setFontSize(9.5);
    doc.setTextColor("#222222");
    concept.key_points.forEach((point) => {
      y = wrapText(doc, `•  ${point}`, MARGIN + 2, y, PAGE_WIDTH - MARGIN * 2 - 2);
    });

    y += 5; // spacing before next concept
    doc.setDrawColor("#eeeeee");
    doc.line(MARGIN, y - 2.5, PAGE_WIDTH - MARGIN, y - 2.5);
  });

  return doc; // caller decides: doc.save("...") client-side, or doc.output() server-side
}

function wrapText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number
) {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * 4.2;
}

function estimateBlockHeight(concept: Concept) {
  // Rough estimate so we know when to start a new page before overflowing.
  return 12 + concept.key_points.length * 4.5;
}

// ---- Usage in a component ----
//
// "use client";
// import { generateCheatsheet } from "@/lib/cheatsheet";
//
// function DownloadButton({ sectionTitle, concepts }) {
//   return (
//     <button onClick={() => generateCheatsheet(sectionTitle, concepts).save(`${sectionTitle}-cheatsheet.pdf`)}>
//       Download cheat sheet
//     </button>
//   );
// }
